---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ice36all
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbook.yml
  inventory:
    host_vars:
      ice36all:
        ice_install_devel: true
        ice_install_python: true
scenario:
  name: ice36all
verifier:
  name: testinfra
  lint:
    name: flake8
